services:
  hhvm:
    container_name: theodore-test-chain-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 48559:10641
